package com.notify2email.app.domain.formatter

import com.notify2email.app.domain.model.EventType
import com.notify2email.app.util.TimeUtils

object EventFormatter {

    /**
     * Formats an event into a professional HTML string for email output.
     * Includes color-coded headers and structured tables.
     */
    fun formatEventHtml(
        type: EventType,
        source: String,
        timestampMillis: Long,
        content: String,
        customTypeLabel: String? = null
    ): String {
        val title = customTypeLabel ?: when (type) {
            EventType.SMS -> "SMS Message"
            EventType.CALL -> "Phone Call"
            EventType.NOTIFICATION -> "App Notification"
        }

        val accentColor = when (type) {
            EventType.SMS -> "#3b82f6" // Blue
            EventType.CALL -> "#10b981" // Green
            EventType.NOTIFICATION -> "#8b5cf6" // Purple
        }

        val readableTime = TimeUtils.formatDateTime(timestampMillis)

        return """
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f8fafc; margin: 0; padding: 20px; color: #1e293b; }
                    .card { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); border: 1px solid #e2e8f0; }
                    .header { background: $accentColor; padding: 24px; color: #ffffff; text-align: center; }
                    .header h1 { margin: 0; font-size: 20px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; }
                    .content { padding: 32px; }
                    .metadata-table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
                    .metadata-table td { padding: 8px 0; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
                    .label { color: #64748b; font-size: 13px; font-weight: 500; width: 100px; }
                    .value { font-weight: 600; color: #0f172a; }
                    .body-section { background: #f1f5f9; padding: 20px; border-radius: 8px; font-size: 15px; line-height: 1.6; color: #334155; white-space: pre-wrap; word-break: break-word; }
                    .footer { padding: 20px; text-align: center; font-size: 12px; color: #94a3b8; }
                </style>
            </head>
            <body>
                <div class="card">
                    <div class="header">
                        <h1>$title</h1>
                    </div>
                    <div class="content">
                        <table class="metadata-table">
                            <tr>
                                <td class="label">Source:</td>
                                <td class="value">${source.ifBlank { "Unknown" }}</td>
                            </tr>
                            <tr>
                                <td class="label">Created at:</td>
                                <td class="value">$readableTime (system time)</td>
                                <br><br>
                            </tr>
                        </table>
                        
                        <div style="font-size: 13px; font-weight: 700; color: #64748b; margin-bottom: 8px; text-transform: uppercase;">Details</div>
                        <div class="body-section">${content.trim()}</div>
                    </div>
                    <div class="footer">
                        <br><br>
                        Generated by <b>Notify2Email</b> • ${System.currentTimeMillis()}
                    </div>
                </div>
            </body>
            </html>
        """.trimIndent()
    }

    /**
     * Formats multiple events into a professional HTML string for batched email output.
     */
    fun formatBatchHtml(
        events: List<BatchEventData>,
        generatedAtMillis: Long
    ): String {
        val totalCount = events.size
        val readableTime = TimeUtils.formatDateTime(generatedAtMillis)

        val eventsHtml = events.joinToString("") { event ->
            val accentColor = when (event.type) {
                EventType.SMS -> "#3b82f6"
                EventType.CALL -> "#10b981"
                EventType.NOTIFICATION -> "#8b5cf6"
            }
            val typeLabel = event.typeLabel ?: when (event.type) {
                EventType.SMS -> "SMS"
                EventType.CALL -> "CALL"
                EventType.NOTIFICATION -> "NOTIF"
            }

            """
            <div style="margin-bottom: 20px; border-left: 4px solid $accentColor; padding-left: 15px;">
                <div style="font-size: 11px; font-weight: 700; color: $accentColor; margin-bottom: 4px;">
                    $typeLabel • ${TimeUtils.formatDateTime(event.timestampMillis)}
                </div>
                <div style="font-weight: 600; color: #0f172a; margin-bottom: 2px;">${event.source.ifBlank { "Unknown Source" }}</div>
                <div style="font-size: 14px; color: #475569; line-height: 1.4;">${event.content.trim()}</div>
            </div>
            """.trimIndent()
        }

        return """
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f8fafc; margin: 0; padding: 20px; color: #1e293b; }
                    .card { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); border: 1px solid #e2e8f0; }
                    .header { background: #1e293b; padding: 24px; color: #ffffff; text-align: center; }
                    .header h1 { margin: 0; font-size: 18px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; }
                    .content { padding: 32px; }
                    .footer { padding: 20px; text-align: center; font-size: 12px; color: #94a3b8; }
                    .stats { margin-bottom: 32px; padding-bottom: 16px; border-bottom: 1px solid #f1f5f9; display: flex; justify-content: space-between; font-size: 13px; color: #64748b; }
                </style>
            </head>
            <body>
                <div class="card">
                    <div class="header">
                        <h1>Events Digest</h1>
                    </div>
                    <div class="content">
                        <div class="stats">
                            <span><b>$totalCount</b> events captured</span><br>
                            <span>Created at: $readableTime (system time)</span>
                            <br>
                        </div>
                        <br>
                        $eventsHtml
                    </div>
                    <div class="footer">
                        Sent via <b>Notify2Email App</b> • ${System.currentTimeMillis()}
                    </div>
                </div>
            </body>
            </html>
        """.trimIndent()
    }

    data class BatchEventData(
        val type: EventType,
        val typeLabel: String? = null,
        val source: String,
        val timestampMillis: Long,
        val content: String
    )
}
